name: publish-release
on:
  push:
    tags:
      - "*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: p1ngod/wildfly-mariadb
          tags: type=ref,event=tag
      - name: Docker meta ImageMagick
        id: meta_im
        uses: docker/metadata-action@v3
        with:
          images: p1ngod/wildfly-mariadb-imagemagick
          tags: type=ref,event=tag
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push ImageMagick
        id: docker_build_im
        uses: docker/build-push-action@v2
        with:
          file: "Dockerfile-imagemagick"
          push: true
          tags: ${{ steps.meta_im.outputs.tags }}
          labels: ${{ steps.meta_im.outputs.labels }}
