name: Scan Docker repo and build images
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      max_age_in_minutes:
        description: 'The maximum age of a tag while scanning the Docker repo'
        required: false
        default: '1440'
jobs:
  scan:
    name: Find Recent Updates
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filter_tags.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set ENV vars
        run: |
          INPUT_MAX_AGE_IN_MINUTES=${{ github.event.inputs.max_age_in_minutes }}
          echo "MAX_AGE_IN_MINUTES=${INPUT_MAX_AGE_IN_MINUTES:-1400}" >> $GITHUB_ENV
      - name: Read major version file
        run: "cat version.properties >> $GITHUB_ENV" 
      - name: Scan Docker Repository
        uses: dhet/scan-docker-tags-action@v1.0.1
        with:
          image: bitnami/wildfly
          max-age-minutes: ${{ env.MAX_AGE_IN_MINUTES }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        id: scan
      - name: Filter tags
        uses: ./.github/actions/filter-tags
        with:
          tags: ${{ steps.scan.outputs.tags }}
          major: ${{ env.WILDFLY_MAJOR_VERSION }}
        id: filter_tags
      - name: Print
        run: "echo 'Recent updates: ${{ steps.filter_tags.outputs.tags }}'"
  build:
    name: Build docker images
    needs: scan
    runs-on: ubuntu-latest
    if: needs.scan.outputs.tag_count != '0'
    strategy:
      matrix: ${{fromJSON(needs.scan.outputs.matrix)}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Print
        run: "echo 'Building docker image for base image \"bitnami/wildfly:${{ matrix.tag }}\"'"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: p1ngod/wildfly-mariadb
          tags: |
            type=raw,value=${{ matrix.tag }}
      - name: Docker meta ImageMagick
        id: meta_im
        uses: docker/metadata-action@v4
        with:
          images: p1ngod/wildfly-mariadb-imagemagick
          tags: |
            type=raw,value=${{ matrix.tag }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            WILDFLY_IMAGE=bitnami/wildfly:${{ matrix.tag }}
      - name: Build and push ImageMagick
        id: docker_build_im
        uses: docker/build-push-action@v3
        with:
          file: "Dockerfile-imagemagick"
          push: true
          tags: ${{ steps.meta_im.outputs.tags }}
          labels: ${{ steps.meta_im.outputs.labels }}
          build-args: |
            WILDFLY_IMAGE=bitnami/wildfly:${{ matrix.tag }}