name: Scan Docker Repo
on:
  workflow_dispatch:

jobs:
  scan:
    name: Find Recent Updates
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filter_tags.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scan Docker Repository
        uses: dhet/scan-docker-tags-action@v1.0.1
        with:
          image: bitnami/wildfly
          max-age-minutes: 7200
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        id: scan
      - name: Filter tags
        uses: ./.github/actions/filter-tags
        with:
          tags: ${{ steps.scan.outputs.tags }}
          major: 26
        id: filter_tags
      - name: Print
        run: "echo 'Recent updates: ${{ steps.filter_tags.outputs.tags }}'"
  build:
    name: Build docker images
    needs: scan
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.scan.outputs.matrix)}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Print
        run: "echo 'Building docker image for base image \"bitnami/wildfly:${{ matrix.tag }}\"'"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: p1ngod/wildfly-mariadb
          tags: |
            type=raw,value=${{ matrix.tag }}
      - name: Docker meta ImageMagick
        id: meta_im
        uses: docker/metadata-action@v4
        with:
          images: p1ngod/wildfly-mariadb-imagemagick
          tags: |
            type=raw,value=${{ matrix.tag }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            WILDFLY_IMAGE=bitnami/wildfly:${{ matrix.tag }}
#      - name: Build and push ImageMagick
#        id: docker_build_im
#        uses: docker/build-push-action@v3
#        with:
#          file: "Dockerfile-imagemagick"
#          push: true
#          tags: ${{ steps.meta_im.outputs.tags }}
#          labels: ${{ steps.meta_im.outputs.labels }}